version: '3.8'
services:
  php:
    image: php:8.1-fpm
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
  nginx:
    image: nginx:latest
    ports:
      - '8000:80'
    volumes:
      - ./backend:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mattru_nursing
    volumes:
      - ./backups:/backups
      - ./database/migrations:/docker-entrypoint-initdb.d
      - ./database/seeders:/docker-entrypoint-initdb.d/seeders
  vite:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - '5173:5173'
    command: ['yarn', 'dev', '--host']